version = 1

[[annotations]]
path = [
  "**/*.ipynb",
  "**/README.md",
  "**/.gitattributes",
  "**/.gitignore",
  "REUSE.toml",
]
SPDX-FileCopyrightText = "Ianis Vasilev <ianis@ivasilev.net>"
SPDX-License-Identifier = "Unlicense"

# The REUSE documentation suggests licensing generated files under CC0-1.0 with NONE as author.
# https://reuse.software/faq/#exclude-file
[[annotations]]
path = [
  "etc/html_cache/*.html",
  "aor24/data/*.txt",
]
precedence = "override"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
